name: Build and Upload Python Package

on:
  push:
    tags:
      - '*'

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build

  build:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
    - name: Build package
      run: python -m build

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download twine
      run: |
        python -m pip install --upgrade twine

    - name: Publish package
      run: |
        python -m twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
